# Generated by Django 2.0.8 on 2018-09-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
