# Generated by Django 2.0.8 on 2018-09-01 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180901_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete='models.CASCADE', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
