# Generated by Django 2.0.8 on 2018-09-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180901_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='subject.subject'),
        ),
    ]
